//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvcWithSQLserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSULTA()
        {
            this.INTERNACAO = new HashSet<INTERNACAO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_PACIENTE { get; set; }
        public Nullable<int> ID_MEDICO { get; set; }
        public Nullable<int> ID_HOSPITAL { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string DIAGNOSTICO { get; set; }
    
        public virtual HOSPITAL HOSPITAL { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERNACAO> INTERNACAO { get; set; }
    }
}
