//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvcWithSQLserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNACAO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ENTRADA { get; set; }
        public Nullable<int> QUARTO { get; set; }
        public Nullable<System.DateTime> SAIDA { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<int> ID_CONSULTA { get; set; }
    
        public virtual CONSULTA CONSULTA { get; set; }
    }
}
